"""initial_schema

Revision ID: b87c2fb0e734
Revises: 
Create Date: 2026-07-10 17:30:10.314092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b87c2fb0e734'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('DOCENTE', 'ANALISTA', 'TECNICO', 'AUXILIAR', name='tipocargo'), nullable=False),
    sa.Column('carga_horaria_padrao', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perfil',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('servidor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('tabela_comissao',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('simbolo', sa.String(length=10), nullable=False),
    sa.Column('valor_comissao', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data_inicio_vigencia', sa.Date(), nullable=False),
    sa.Column('data_fim_vigencia', sa.Date(), server_default=sa.text("'9999-12-31'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tabela_gstu',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo_gstu', sa.String(length=30), nullable=False),
    sa.Column('grau', sa.String(length=10), nullable=False),
    sa.Column('referencia', sa.String(length=10), nullable=False),
    sa.Column('valor_gstu', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data_inicio_vigencia', sa.Date(), nullable=False),
    sa.Column('data_fim_vigencia', sa.Date(), server_default=sa.text("'9999-12-31'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tabela_vencimento',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo_vencimento', sa.String(length=20), nullable=False),
    sa.Column('classe', sa.String(length=50), nullable=False),
    sa.Column('nivel_grau', sa.String(length=10), nullable=False),
    sa.Column('carga_horaria', sa.Integer(), nullable=False),
    sa.Column('valor_base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data_inicio_vigencia', sa.Date(), nullable=False),
    sa.Column('data_fim_vigencia', sa.Date(), server_default=sa.text("'9999-12-31'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('tabela_afetada', sa.String(length=50), nullable=False),
    sa.Column('registro_id', sa.Uuid(), nullable=False),
    sa.Column('operacao', sa.Enum('INSERT', 'UPDATE', 'DELETE', 'LOGIN', 'SIMULACAO_EXECUCAO', name='operacaolog'), nullable=False),
    sa.Column('payload_antigo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload_novo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_origem', sa.String(length=45), server_default=sa.text("'0.0.0.0'"), nullable=False),
    sa.Column('data_hora', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulacao',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.Enum('INDIVIDUAL', 'LOTE', name='tiposimulacao'), nullable=False),
    sa.Column('status', sa.Enum('RASCUNHO', 'PROCESSANDO', 'FINALIZADO', 'ERRO', name='statussimulacao'), nullable=False),
    sa.Column('criado_por_usuario_id', sa.Uuid(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['criado_por_usuario_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_perfil',
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('perfil_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'perfil_id')
    )
    op.create_table('vinculo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('servidor_id', sa.Uuid(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('data_admissao', sa.Date(), nullable=False),
    sa.Column('cargo_id', sa.Uuid(), nullable=False),
    sa.Column('regime_previdenciario', sa.Enum('BAPREV_REGIME_PROPRIO', 'PREVBAHIA_COMPLEMENTAR', name='regimeprevidenciario'), nullable=False),
    sa.Column('participante_prev_complementar', sa.Boolean(), nullable=False),
    sa.Column('aliquota_coparticipacao_complementar', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('tipo_vinculo', sa.Enum('ESTATUTARIO', 'REDA', 'CLT', name='tipovinculo'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidor.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('averbacao',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vinculo_id', sa.Uuid(), nullable=False),
    sa.Column('dias_averbados', sa.Integer(), nullable=False),
    sa.Column('tipo_averbacao', sa.Enum('ATS', 'APOSENTADORIA', name='tipoaverbacao'), nullable=False),
    sa.Column('data_averbacao', sa.Date(), nullable=False),
    sa.Column('processo_numero', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['vinculo_id'], ['vinculo.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_funcional',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vinculo_id', sa.Uuid(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), server_default=sa.text("'9999-12-31'"), nullable=False),
    sa.Column('tabela_vencimento_id', sa.Uuid(), nullable=False),
    sa.Column('tabela_gstu_id', sa.Uuid(), nullable=True),
    sa.Column('cet_percentual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('insalubridade_percentual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vpess_valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tabela_comissao_id', sa.Uuid(), nullable=True),
    sa.Column('percentual_estabilizado', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['tabela_comissao_id'], ['tabela_comissao.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tabela_gstu_id'], ['tabela_gstu.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tabela_vencimento_id'], ['tabela_vencimento.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vinculo_id'], ['vinculo.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulacao_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('simulacao_id', sa.Uuid(), nullable=False),
    sa.Column('vinculo_id', sa.Uuid(), nullable=False),
    sa.Column('data_vigencia_proposta', sa.Date(), nullable=False),
    sa.Column('mes_gozo_ferias_proposto', sa.Integer(), nullable=False),
    sa.Column('dados_origem_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dados_propostos_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resultado_calculo_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('justificativa_requisitos', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['simulacao_id'], ['simulacao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vinculo_id'], ['vinculo.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulacao_item')
    op.drop_table('historico_funcional')
    op.drop_table('averbacao')
    op.drop_table('vinculo')
    op.drop_table('usuario_perfil')
    op.drop_table('simulacao')
    op.drop_table('audit_log')
    op.drop_table('usuario')
    op.drop_table('tabela_vencimento')
    op.drop_table('tabela_gstu')
    op.drop_table('tabela_comissao')
    op.drop_table('servidor')
    op.drop_table('perfil')
    op.drop_table('cargo')
    # ### end Alembic commands ###
